import type { Era } from './types';
import { Icons } from './components/Icons';

export const HISTORICAL_ERAS: Era[] = [
  {
    id: 'prehistory',
    name: { en: 'Prehistory', fr: 'Préhistoire' },
    period: { en: 'c. 40,000 - 4,000 BC', fr: 'env. 40 000 - 4 000 av. J.-C.' },
    description: {
      en: 'The age before written records, marked by the rise of Homo sapiens, cave art, and the first human societies.',
      fr: 'L\'âge avant les archives écrites, marqué par l\'essor de l\'Homo sapiens, l\'art rupestre et les premières sociétés humaines.',
    },
    icon: Icons.Prehistory,
    color: 'bg-orange-900/50 border-orange-600',
    styles: {
      en: ['Cro-Magnon Hunter', 'Lascaux Cave Artist', 'Neolithic Villager'],
      fr: ['Chasseur Cro-Magnon', 'Artiste de Lascaux', 'Villageois Néolithique'],
    },
    image: 'https://picsum.photos/seed/prehistory/800/600',
    keyEvents: {
      en: ['Development of stone tools', 'Creation of famous cave paintings (Lascaux, Chauvet)', 'The Agricultural Revolution'],
      fr: ['Développement des outils en pierre', 'Création de célèbres peintures rupestres (Lascaux, Chauvet)', 'La Révolution agricole'],
    },
    culturalFacts: {
      en: ['The first musical instruments, like bone flutes, were created', 'Early humans developed complex belief systems and burial rituals', 'Megalithic structures like Stonehenge were built'],
      fr: ['Les premiers instruments de musique, comme les flûtes en os, ont été créés', 'Les premiers humains ont développé des systèmes de croyances complexes et des rituels funéraires', 'Des structures mégalithiques comme Stonehenge ont été construites'],
    },
    clothingStyles: {
      en: ['Animal hides and furs', 'Simple leather loincloths and tunics', 'Jewelry made from shells, bones, and teeth'],
      fr: ['Peaux d\'animaux et fourrures', 'Simples pagnes et tuniques en cuir', 'Bijoux faits de coquillages, d\'os et de dents'],
    },
    ambianceSfx: 'https://cdn.pixabay.com/audio/2022/10/25/audio_553250b33b.mp3',
  },
  {
    id: 'pharaonic_egypt',
    name: { en: 'Pharaonic Egypt', fr: 'Égypte Pharaonique' },
    period: { en: 'c. 3100 - 30 BC', fr: 'env. 3100 - 30 av. J.-C.' },
    description: {
      en: 'A majestic civilization in Northeast Africa, known for its monumental pyramids, pharaohs, and complex mythology.',
      fr: 'Une civilisation majestueuse en Afrique du Nord-Est, connue pour ses pyramides monumentales, ses pharaons et sa mythologie complexe.',
    },
    icon: Icons.PharaonicEgypt,
    color: 'bg-yellow-900/50 border-yellow-500',
    styles: {
      en: ['Reigning Pharaoh', 'Scribe of Thoth', 'Priestess of Isis'],
      fr: ['Pharaon Régnant', 'Scribe de Thot', 'Prêtresse d\'Isis'],
    },
    image: 'https://picsum.photos/seed/egypt/800/600',
    keyEvents: {
      en: ['Unification of Upper and Lower Egypt', 'Building of the Great Pyramids of Giza', 'Reign of powerful pharaohs like Tutankhamun and Cleopatra'],
      fr: ['Unification de la Haute et de la Basse-Égypte', 'Construction des Grandes Pyramides de Gizeh', 'Règne de puissants pharaons comme Toutânkhamon et Cléopâtre'],
    },
    culturalFacts: {
      en: ['Development of hieroglyphic writing', 'Advanced knowledge of medicine and mathematics', 'Complex religious beliefs centered on an afterlife and mummification'],
      fr: ['Développement de l\'écriture hiéroglyphique', 'Connaissances avancées en médecine et en mathématiques', 'Croyances religieuses complexes centrées sur l\'au-delà et la momification'],
    },
    clothingStyles: {
      en: ['White linen kilts (schenti) for men', 'Simple sheath dresses (kalasiris) for women', 'Elaborate wigs, headdresses, and heavy kohl eyeliner'],
      fr: ['Kilts en lin blanc (schenti) pour les hommes', 'Robes fourreaux simples (kalasiris) pour les femmes', 'Perruques élaborées, coiffes et eye-liner khôl épais'],
    },
    ambianceSfx: 'https://cdn.pixabay.com/audio/2022/09/20/audio_03d2836217.mp3',
  },
  {
    id: 'antiquity',
    name: { en: 'Greco-Roman Antiquity', fr: 'Antiquité Gréco-Romaine' },
    period: { en: 'c. 800 BC - 500 AD', fr: 'env. 800 av. J.-C. - 500 ap. J.-C.' },
    description: {
      en: 'The cradle of Western civilization, featuring epic philosophy, democracy, monumental architecture, and powerful empires.',
      fr: 'Le berceau de la civilisation occidentale, avec sa philosophie épique, sa démocratie, son architecture monumentale et ses empires puissants.',
    },
    icon: Icons.Antiquity,
    color: 'bg-stone-700/50 border-stone-400',
    styles: {
      en: ['Roman Senator in a Toga', 'Greek Philosopher in Athens', 'Spartan Warrior'],
      fr: ['Sénateur Romain en Toge', 'Philosophe Grec à Athènes', 'Guerrier Spartiate'],
    },
    image: 'https://picsum.photos/seed/antiquity/800/600',
    keyEvents: {
      en: ['The founding of Rome', 'The Golden Age of Athens under Pericles', 'The rise and fall of the Roman Empire'],
      fr: ['La fondation de Rome', 'L\'Âge d\'or d\'Athènes sous Périclès', 'L\'ascension et la chute de l\'Empire romain'],
    },
    culturalFacts: {
      en: ['Birthplace of democracy, philosophy, and theater', 'Roman engineering marvels like aqueducts and the Colosseum', 'The Olympic Games were founded in ancient Greece'],
      fr: ['Lieu de naissance de la démocratie, de la philosophie et du théâtre', 'Merveilles de l\'ingénierie romaine comme les aqueducs et le Colisée', 'Les Jeux Olympiques ont été fondés en Grèce antique'],
    },
    clothingStyles: {
      en: ['Simple tunics (chiton) and draped cloaks (himation) for Greeks', 'The iconic toga for Roman citizens', 'Leather sandals (caligae) for soldiers'],
      fr: ['Tuniques simples (chiton) et manteaux drapés (himation) pour les Grecs', 'L\'emblématique toge pour les citoyens romains', 'Sandales en cuir (caligae) pour les soldats'],
    },
    ambianceSfx: 'https://cdn.pixabay.com/audio/2024/05/10/audio_2e8f1a1467.mp3',
  },
  {
    id: 'middle_ages',
    name: { en: 'Middle Ages', fr: 'Moyen Âge' },
    period: { en: 'c. 500 - 1500 AD', fr: 'env. 500 - 1500' },
    description: {
      en: 'An era of knights, castles, and cathedrals, stretching from the fall of Rome to the dawn of the Renaissance.',
      fr: 'Une ère de chevaliers, de châteaux et de cathédrales, s\'étendant de la chute de Rome à l\'aube de la Renaissance.',
    },
    icon: Icons.MiddleAges,
    color: 'bg-slate-700/50 border-slate-400',
    styles: {
      en: ['Knight in Shining Armor', 'Gothic Cathedral Artisan', 'Medieval Court Jester'],
      fr: ['Chevalier en Armure Étincelante', 'Artisan de Cathédrale Gothique', 'Bouffon de Cour Médiéval'],
    },
    image: 'https://picsum.photos/seed/middleages/800/600',
    keyEvents: {
      en: ['The Viking Age', 'The signing of the Magna Carta', 'The Black Death pandemic'],
      fr: ['L\'Âge des Vikings', 'La signature de la Magna Carta', 'La pandémie de la Peste Noire'],
    },
    culturalFacts: {
      en: ['The feudal system structured society', 'Monks in monasteries preserved ancient knowledge', 'The first universities were established in Europe'],
      fr: ['Le système féodal structurait la société', 'Les moines dans les monastères préservaient les connaissances anciennes', 'Les premières universités ont été établies en Europe'],
    },
    clothingStyles: {
      en: ['Chainmail and plate armor for knights', 'Linen tunics and woolen cloaks for commoners', 'Pointed shoes (poulaines) and elaborate headdresses (hennins) for nobility'],
      fr: ['Cotte de mailles et armure de plaques pour les chevaliers', 'Tuniques en lin et manteaux en laine pour les roturiers', 'Chaussures pointues (poulaines) et coiffes élaborées (hennins) pour la noblesse'],
    },
    ambianceSfx: 'https://cdn.pixabay.com/audio/2022/02/01/audio_eb3661643c.mp3',
  },
  {
    id: 'renaissance',
    name: { en: 'Renaissance', fr: 'Renaissance' },
    period: { en: 'c. 1400 - 1600 AD', fr: 'env. 1400 - 1600' },
    description: {
      en: 'A fervent period of European cultural, artistic, political, and economic "rebirth" following the Middle Ages.',
      fr: 'Une période fervente de "renaissance" culturelle, artistique, politique et économique en Europe après le Moyen Âge.',
    },
    icon: Icons.Renaissance,
    color: 'bg-rose-900/50 border-rose-500',
    styles: {
      en: ['Da Vinci-esque Inventor', 'Florentine Noble', 'Shakespearean Actor'],
      fr: ['Inventeur à la De Vinci', 'Noble Florentin', 'Acteur Shakespearien'],
    },
    image: 'https://picsum.photos/seed/renaissance/800/600',
    keyEvents: {
      en: ['The invention of the printing press by Gutenberg', 'The works of Leonardo da Vinci and Michelangelo', 'The Age of Exploration begins'],
      fr: ['L\'invention de l\'imprimerie par Gutenberg', 'Les œuvres de Léonard de Vinci et Michel-Ange', 'Le début de l\'Âge des Grandes Découvertes'],
    },
    culturalFacts: {
      en: ['A renewed interest in classical Greek and Roman culture', 'Humanism, a philosophy focusing on human potential, gained prominence', 'The powerful Medici family were major patrons of the arts'],
      fr: ['Un intérêt renouvelé pour la culture classique grecque et romaine', 'L\'humanisme, une philosophie axée sur le potentiel humain, a gagné en importance', 'La puissante famille Médicis était un mécène majeur des arts'],
    },
    clothingStyles: {
      en: ['Luxurious fabrics like velvet and silk', 'Voluminous sleeves, ruffs, and doublets for men', 'Corsets, farthingales, and elaborate gowns for women'],
      fr: ['Tissus luxueux comme le velours et la soie', 'Manches volumineuses, fraises et pourpoints pour les hommes', 'Corsets, vertugadins et robes élaborées pour les femmes'],
    },
    ambianceSfx: 'https://cdn.pixabay.com/audio/2022/08/23/audio_4043f11463.mp3',
  },
  {
    id: 'dynastic_china',
    name: { en: 'Dynastic China', fr: 'Chine Dynastique' },
    period: { en: 'c. 618 - 1644 AD (Tang/Ming)', fr: 'env. 618 - 1644 (Tang/Ming)' },
    description: { en: 'Journey to the golden age of Chinese culture and innovation, a time of majestic palaces, silk robes, and profound philosophy.', fr: 'Voyagez vers l\'âge d\'or de la culture et de l\'innovation chinoises, une époque de palais majestueux, de robes de soie et de philosophie profonde.'},
    icon: Icons.DynasticChina,
    color: 'bg-red-900/50 border-red-500',
    styles: { en: ['Tang Dynasty Court Noble', 'Ming Dynasty Scholar', 'Imperial Silk Painter'], fr: ['Noble de la Cour des Tang', 'Érudit de la Dynastie Ming', 'Peintre Impérial sur Soie'] },
    image: 'https://picsum.photos/seed/china/800/600',
    keyEvents: { en: ['Invention of gunpowder and printing', 'Construction of the Forbidden City', 'Voyages of Zheng He'], fr: ['Invention de la poudre à canon et de l\'imprimerie', 'Construction de la Cité Interdite', 'Voyages de Zheng He'] },
    culturalFacts: { en: ['The Silk Road connected China to the West', 'Calligraphy was considered the highest art form', 'The imperial examination system selected state officials'], fr: ['La Route de la Soie reliait la Chine à l\'Occident', 'La calligraphie était considérée comme la forme d\'art la plus élevée', 'Le système d\'examen impérial sélectionnait les fonctionnaires de l\'État'] },
    clothingStyles: { en: ['Elegant silk robes (hanfu)', 'Intricate embroidery with dragon and phoenix motifs', 'Elaborate hairstyles with pins and ornaments'], fr: ['Élégantes robes de soie (hanfu)', 'Broderies complexes avec des motifs de dragon et de phénix', 'Coiffures élaborées avec des épingles et des ornements'] },
    ambianceSfx: 'https://cdn.pixabay.com/audio/2022/02/07/audio_73295f159a.mp3',
  },
  {
    id: 'feudal_japan',
    name: { en: 'Feudal Japan', fr: 'Japon Féodal' },
    period: { en: 'c. 1603 - 1868 AD (Edo Period)', fr: 'env. 1603 - 1868 (Période Edo)' },
    description: { en: 'Step into the world of samurai warriors, elegant geishas, and the vibrant arts of the Edo period under the rule of the shoguns.', fr: 'Entrez dans le monde des samouraïs, des geishas élégantes et des arts vibrants de la période Edo sous le règne des shoguns.' },
    icon: Icons.FeudalJapan,
    color: 'bg-indigo-900/50 border-indigo-500',
    styles: { en: ['Honorable Samurai Warrior', 'Graceful Geisha in Kyoto', 'Ukiyo-e Woodblock Artist'], fr: ['Honorable Samouraï', 'Gracieuse Geisha à Kyoto', 'Artiste d\'estampes Ukiyo-e'] },
    image: 'https://picsum.photos/seed/japan/800/600',
    keyEvents: { en: ['Establishment of the Tokugawa Shogunate', 'Period of national isolation (sakoku)', 'Flourishing of Kabuki theater and Sumo wrestling'], fr: ['Établissement du shogunat Tokugawa', 'Période d\'isolement national (sakoku)', 'Floraison du théâtre Kabuki et de la lutte Sumo'] },
    culturalFacts: { en: ['The samurai followed a strict code of conduct called Bushido', 'Ukiyo-e, or "pictures of the floating world," became a major art form', 'Haiku poetry was perfected by masters like Bashō'], fr: ['Les samouraïs suivaient un code de conduite strict appelé Bushido', 'L\'Ukiyo-e, ou "images du monde flottant", est devenu une forme d\'art majeure', 'La poésie Haïku a été perfectionnée par des maîtres comme Bashō'] },
    clothingStyles: { en: ['Layered kimonos with intricate patterns', 'Samurai armor (yoroi) and helmets (kabuto)', 'Traditional geta sandals and tabi socks'], fr: ['Kimonos superposés aux motifs complexes', 'Armures de samouraï (yoroi) et casques (kabuto)', 'Sandales traditionnelles geta et chaussettes tabi'] },
    ambianceSfx: 'https://cdn.pixabay.com/audio/2023/07/22/audio_eb7e1ff76c.mp3',
  },
  {
    id: 'mesoamerican_empires',
    name: { en: 'Mesoamerican Empires', fr: 'Empires Mésoaméricains' },
    period: { en: 'c. 250 - 1521 AD', fr: 'env. 250 - 1521' },
    description: { en: 'Explore the mystique of the Maya, Aztec, and Inca civilizations, known for their towering pyramids, intricate calendars, and rich mythologies.', fr: 'Explorez le mystère des civilisations Maya, Aztèque et Inca, connues pour leurs pyramides imposantes, leurs calendriers complexes et leurs riches mythologies.' },
    icon: Icons.Mesoamerican,
    color: 'bg-teal-900/50 border-teal-500',
    styles: { en: ['Aztec Eagle Warrior', 'Mayan High Priestess', 'Incan Royal'], fr: ['Guerrier Aigle Aztèque', 'Grande Prêtresse Maya', 'Noble Inca'] },
    image: 'https://picsum.photos/seed/mesoamerica/800/600',
    keyEvents: { en: ['Construction of city-states like Tikal and Chichen Itza', 'Development of complex writing and calendar systems', 'Building of the vast Inca road network'], fr: ['Construction de cités-états comme Tikal et Chichen Itza', 'Développement de systèmes d\'écriture et de calendriers complexes', 'Construction du vaste réseau routier Inca'] },
    culturalFacts: { en: ['The Maya developed a sophisticated understanding of astronomy', 'The Aztecs built their capital, Tenochtitlan, on an island in a lake', 'The Inca practiced cranial deformation for aesthetic reasons'], fr: ['Les Mayas ont développé une compréhension sophistiquée de l\'astronomie', 'Les Aztèques ont construit leur capitale, Tenochtitlan, sur une île dans un lac', 'Les Incas pratiquaient la déformation crânienne pour des raisons esthétiques'] },
    clothingStyles: { en: ['Colorful woven textiles and cloaks (tilmàtli)', 'Elaborate headdresses made of quetzal feathers', 'Jewelry made from jade, gold, and turquoise'], fr: ['Textiles tissés colorés et manteaux (tilmàtli)', 'Coiffes élaborées en plumes de quetzal', 'Bijoux en jade, or et turquoise'] },
    ambianceSfx: 'https://cdn.pixabay.com/audio/2023/09/27/audio_d1e8c78c2e.mp3',
  },
  {
    id: 'victorian',
    name: { en: 'Victorian Era', fr: 'Époque Victorienne' },
    period: { en: '1837 - 1901', fr: '1837 - 1901' },
    description: {
      en: 'A time of industrial revolution, scientific discovery, and strict social mores under the long reign of Queen Victoria.',
      fr: 'Une époque de révolution industrielle, de découvertes scientifiques et de mœurs sociales strictes sous le long règne de la reine Victoria.',
    },
    icon: Icons.Victorian,
    color: 'bg-gray-800/50 border-gray-500',
    styles: {
      en: ['Industrial Revolution Inventor', 'High Society Lady at a Ball', 'Sherlock Holmes-style Detective'],
      fr: ['Inventeur de la Révolution Industrielle', 'Dame de la Haute Société à un Bal', 'Détective style Sherlock Holmes'],
    },
    image: 'https://picsum.photos/seed/victorian/800/600',
    keyEvents: {
      en: ['The Great Exhibition of 1851', 'Publication of Darwin\'s "On the Origin of Species"', 'The construction of the London Underground'],
      fr: ['La Grande Exposition de 1851', 'Publication de "De l\'origine des espèces" de Darwin', 'La construction du métro de Londres'],
    },
    culturalFacts: {
      en: ['The rise of the novel as a major literary form (Dickens, Brontë sisters)', 'A fascination with spiritualism and the supernatural', 'Strict etiquette governed all aspects of public and private life'],
      fr: ['L\'essor du roman comme forme littéraire majeure (Dickens, les sœurs Brontë)', 'Une fascination pour le spiritisme et le surnaturel', 'Une étiquette stricte régissait tous les aspects de la vie publique et privée'],
    },
    clothingStyles: {
      en: ['Corsets, bustles, and large crinoline skirts for women', 'Top hats, frock coats, and waistcoats for men', 'Mourning clothes were worn for extended periods'],
      fr: ['Corsets, tournures et grandes jupes à crinoline pour les femmes', 'Chapeaux haut-de-forme, redingotes et gilets pour les hommes', 'Les vêtements de deuil étaient portés pendant de longues périodes'],
    },
    ambianceSfx: 'https://cdn.pixabay.com/audio/2023/10/24/audio_32c021a8d0.mp3',
  },
  {
    id: 'art_nouveau',
    name: { en: 'Art Nouveau', fr: 'Art Nouveau' },
    period: { en: 'c. 1890 - 1910', fr: 'env. 1890 - 1910' },
    description: { en: 'An ornamental style of art, architecture, and design characterized by its use of long, sinuous, organic lines and floral motifs.', fr: 'Un style ornemental d\'art, d\'architecture et de design caractérisé par son utilisation de longues lignes sinueuses et organiques et de motifs floraux.' },
    icon: Icons.ArtNouveau,
    color: 'bg-emerald-900/50 border-emerald-500',
    styles: { en: ['Alphonse Mucha-style portrait', 'Figure in a Tiffany stained glass window', 'Person surrounded by organic, whiplash curves'], fr: ['Portrait style Alphonse Mucha', 'Personnage dans un vitrail Tiffany', 'Personne entourée de courbes organiques "coup de fouet"'] },
    image: 'https://picsum.photos/seed/artnouveau/800/600',
    keyEvents: { en: ['Paris Exposition Universelle of 1900 showcases the style', 'Hector Guimard designs the iconic Paris Métro entrances', 'Gustav Klimt paints "The Kiss"'], fr: ['L\'Exposition Universelle de Paris de 1900 met en valeur le style', 'Hector Guimard conçoit les entrées emblématiques du Métro de Paris', 'Gustav Klimt peint "Le Baiser"'] },
    culturalFacts: { en: ['The style sought to break down the traditional distinction between fine arts and applied arts', 'It was known by different names across Europe: Jugendstil in Germany, Stile Liberty in Italy', 'Art Nouveau was heavily influenced by Japanese art and woodblock prints'], fr: ['Le style cherchait à briser la distinction traditionnelle entre les beaux-arts et les arts appliqués', 'Il était connu sous différents noms en Europe : Jugendstil en Allemagne, Stile Liberty en Italie', 'L\'Art Nouveau a été fortement influencé par l\'art et les estampes japonaises'] },
    clothingStyles: { en: ['Long, flowing dresses with S-curve silhouettes', 'Natural motifs like dragonflies, orchids, and irises', 'Lavish use of delicate fabrics, lace, and embroidery'], fr: ['Longues robes fluides avec des silhouettes en S', 'Motifs naturels comme les libellules, les orchidées et les iris', 'Utilisation somptueuse de tissus délicats, de dentelle et de broderies'] },
    ambianceSfx: 'https://cdn.pixabay.com/audio/2024/02/10/audio_502157c152.mp3',
  },
  {
    id: 'twenties',
    name: { en: 'Roaring Twenties', fr: 'Années Folles' },
    period: { en: '1920 - 1929', fr: '1920 - 1929' },
    description: {
      en: 'A decade of economic growth and widespread social change, known for its jazz music, flapper fashion, and Art Deco style.',
      fr: 'Une décennie de croissance économique et de profonds changements sociaux, connue pour sa musique jazz, sa mode garçonne et son style Art Déco.',
    },
    icon: Icons.Twenties,
    color: 'bg-yellow-800/50 border-yellow-400',
    styles: {
      en: ['Jazz Age Flapper', 'Silent Film Star', 'Art Deco Speakeasy Patron'],
      fr: ['Garçonne de l\'Âge du Jazz', 'Star du Cinéma Muet', 'Client d\'un Speakeasy Art Déco'],
    },
    image: 'https://picsum.photos/seed/twenties/800/600',
    keyEvents: {
      en: ['The beginning of mass radio broadcasting', 'The discovery of Tutankhamun\'s tomb', 'The Wall Street Crash of 1929'],
      fr: ['Le début de la radiodiffusion de masse', 'La découverte du tombeau de Toutânkhamon', 'Le Krach de Wall Street de 1929'],
    },
    culturalFacts: {
      en: ['The "flapper" became a symbol of a new, liberated woman', 'Jazz music flourished in cities like New Orleans, Chicago, and New York', 'Prohibition in the US led to the rise of illegal bars called speakeasies'],
      fr: ['La "garçonne" est devenue le symbole d\'une nouvelle femme libérée', 'Le jazz a prospéré dans des villes comme La Nouvelle-Orléans, Chicago et New York', 'La Prohibition aux États-Unis a entraîné l\'essor de bars clandestins appelés speakeasies'],
    },
    clothingStyles: {
      en: ['Drop-waist dresses with beading and fringe', 'Cloche hats and long pearl necklaces', 'Sharp suits and fedoras for men'],
      fr: ['Robes à taille basse avec perles et franges', 'Chapeaux cloches et longs colliers de perles', 'Costumes élégants et fedoras pour les hommes'],
    },
    ambianceSfx: 'https://cdn.pixabay.com/audio/2022/01/24/audio_b72b3c2cb7.mp3',
  },
   {
    id: 'bauhaus',
    name: { en: 'Bauhaus', fr: 'Bauhaus' },
    period: { en: '1919 - 1933', fr: '1919 - 1933' },
    description: { en: 'A revolutionary German school of art and design that combined crafts and fine arts, famous for its functional and geometric aesthetic.', fr: 'Une école d\'art et de design allemande révolutionnaire qui combinait artisanat et beaux-arts, célèbre pour son esthétique fonctionnelle et géométrique.' },
    icon: Icons.Bauhaus,
    color: 'bg-gray-700/50 border-gray-400',
    styles: { en: ['Abstract portrait with primary colors', 'Figure integrated into geometric architecture', 'Typographic poster style of Herbert Bayer'], fr: ['Portrait abstrait avec des couleurs primaires', 'Personnage intégré dans une architecture géométrique', 'Style d\'affiche typographique de Herbert Bayer'] },
    image: 'https://picsum.photos/seed/bauhaus/800/600',
    keyEvents: { en: ['Walter Gropius founds the Bauhaus school in Weimar', 'Artists like Kandinsky and Klee teach at the school', 'The school moves to Dessau and later Berlin before being closed by the Nazis'], fr: ['Walter Gropius fonde l\'école du Bauhaus à Weimar', 'Des artistes comme Kandinsky et Klee enseignent à l\'école', 'L\'école déménage à Dessau puis à Berlin avant d\'être fermée par les nazis'] },
    culturalFacts: { en: ['The core objective was to reunify art, craft, and technology', 'The motto was "Art into Industry"', 'Bauhaus design principles heavily influenced modern architecture and graphic design'], fr: ['L\'objectif principal était de réunifier l\'art, l\'artisanat et la technologie', 'La devise était "L\'art dans l\'industrie"', 'Les principes de design du Bauhaus ont fortement influencé l\'architecture moderne et le design graphique'] },
    clothingStyles: { en: ['Functional, simple clothing with clean lines', 'Geometric patterns and primary color blocks', 'Rejection of ornamentation in favor of practicality'], fr: ['Vêtements fonctionnels et simples aux lignes épurées', 'Motifs géométriques et blocs de couleurs primaires', 'Rejet de l\'ornementation au profit de la praticité'] },
    ambianceSfx: 'https://cdn.pixabay.com/audio/2023/11/23/audio_49609659b8.mp3',
  },
  {
    id: 'pop_art',
    name: { en: 'Pop Art', fr: 'Pop Art' },
    period: { en: '1950s - 1960s', fr: 'Années 1950 - 1960' },
    description: { en: 'An art movement that challenged fine art by including imagery from popular and mass culture, such as advertising and comic books.', fr: 'Un mouvement artistique qui a défié les beaux-arts en incluant des images de la culture populaire et de masse, comme la publicité et les bandes dessinées.' },
    icon: Icons.PopArt,
    color: 'bg-pink-700/50 border-pink-400',
    styles: { en: ['Andy Warhol-style screen print', 'Roy Lichtenstein comic book look', 'Colorful pop art collage'], fr: ['Sérigraphie style Andy Warhol', 'Look bande dessinée de Roy Lichtenstein', 'Collage pop art coloré'] },
    image: 'https://picsum.photos/seed/popart/800/600',
    keyEvents: { en: ['Andy Warhol exhibits his Campbell\'s Soup Cans', 'The Independent Group forms in London, a precursor to Pop Art', 'Roy Lichtenstein creates his first comic strip-inspired paintings'], fr: ['Andy Warhol expose ses Campbell\'s Soup Cans', 'L\'Independent Group se forme à Londres, précurseur du Pop Art', 'Roy Lichtenstein crée ses premières peintures inspirées des bandes dessinées'] },
    culturalFacts: { en: ['Pop Art is widely interpreted as a reaction to the then-dominant ideas of abstract expressionism', 'It used techniques of mass production like screenprinting', 'Artists sought to blur the lines between "high" art and "low" culture'], fr: ['Le Pop Art est largement interprété comme une réaction aux idées alors dominantes de l\'expressionnisme abstrait', 'Il utilisait des techniques de production de masse comme la sérigraphie', 'Les artistes cherchaient à brouiller les frontières entre l\'art "noble" et la culture "populaire"'] },
    clothingStyles: { en: ['Bold patterns, bright colors, and geometric shapes', 'Mini skirts and vinyl dresses', 'Graphic t-shirts and casual wear reflecting consumer culture'], fr: ['Motifs audacieux, couleurs vives et formes géométriques', 'Minijupes et robes en vinyle', 'T-shirts graphiques et vêtements décontractés reflétant la culture de consommation'] },
    ambianceSfx: 'https://cdn.pixabay.com/audio/2022/03/24/audio_34b7f6dd29.mp3',
  },
  {
    id: 'the_2010s',
    name: { en: 'The 2010s', fr: 'Les Années 2010' },
    period: { en: '2010 - 2019', fr: '2010 - 2019' },
    description: { en: 'The age of social media, smartphones, and streaming. A decade defined by hipster aesthetics, influencer culture, and global connectivity.', fr: 'L\'ère des réseaux sociaux, des smartphones et du streaming. Une décennie définie par l\'esthétique hipster, la culture des influenceurs et la connectivité mondiale.' },
    icon: Icons.The2010s,
    color: 'bg-cyan-700/50 border-cyan-400',
    styles: { en: ['Perfectly curated Instagram Influencer', 'TikTok E-girl/E-boy aesthetic', 'Coachella festival-goer'], fr: ['Influenceur/Influenceuse Instagram au feed parfait', 'Esthétique E-girl/E-boy de TikTok', 'Festivalier/Festivalière de Coachella'] },
    image: 'https://picsum.photos/seed/2010s/800/600',
    keyEvents: { en: ['The rise of Instagram and influencer marketing', 'The global phenomenon of "Game of Thrones"', 'The explosion of the Marvel Cinematic Universe'], fr: ['L\'essor d\'Instagram et du marketing d\'influence', 'Le phénomène mondial de "Game of Thrones"', 'L\'explosion de l\'univers cinématographique Marvel'] },
    culturalFacts: { en: ['"Selfie" was the word of the year in 2013', 'Streaming services like Netflix and Spotify became dominant', '"Normcore" and "athleisure" were major fashion trends'], fr: ['"Selfie" a été le mot de l\'année en 2013', 'Les services de streaming comme Netflix et Spotify sont devenus dominants', 'Le "Normcore" et l\'"athleisure" étaient des tendances de mode majeures'] },
    clothingStyles: { en: ['Skinny jeans and graphic tees', 'Flower crowns and bohemian festival wear', 'Athleisure wear like leggings and sneakers as everyday fashion'], fr: ['Jeans skinny et t-shirts graphiques', 'Couronnes de fleurs et tenues de festival bohèmes', 'Vêtements "athleisure" comme les leggings et les baskets comme mode de tous les jours'] },
    ambianceSfx: 'https://cdn.pixabay.com/audio/2023/04/02/audio_403b0d467e.mp3',
  },
];